name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.6'
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: |
          flutter build web --target lib/main_production.dart --release --web-renderer html\
            --dart-define WEB_API_KEY=${{ secrets.WEB_API_KEY }} \
            --dart-define WEB_APP_ID=${{ secrets.WEB_APP_ID }} \
            --dart-define WEB_MESSAGING_SENDER_ID=${{ secrets.WEB_MESSAGING_SENDER_ID }} \
            --dart-define WEB_PROJECT_ID=${{ secrets.WEB_PROJECT_ID }} \
            --dart-define WEB_AUTH_DOMAIN=${{ secrets.WEB_AUTH_DOMAIN }} \
            --dart-define WEB_STORAGE_BUCKET=${{ secrets.WEB_STORAGE_BUCKET }} \
            --dart-define WEB_MEASUREMENT_ID=${{ secrets.WEB_MEASUREMENT_ID }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-web-build
          path: build/web
          retention-days: 1
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: release-web-build
          path: release-web-build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          channelId: live
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GPTPAD_DEV }}'
          projectId: gptpad-dev
